<a href="https://colab.research.google.com/github/himanshusar123/-Machine-Learning-Quiz-Classification-or-Regression-/blob/main/Day_7__USS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [2]:
from google.colab import files
uploaded = files.upload()

df = pd.read_csv("Customer_Loan_Approval_Dataset.csv")

df.head()

Saving Customer_Loan_Approval_Dataset.csv to Customer_Loan_Approval_Dataset.csv

,Application_ID,Gender,Married,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,APP001,Male,Yes,Not Graduate,Yes,5657,1143,238,180,0,Rural,Rejected
1,APP002,Female,Yes,Graduate,Yes,5582,1905,179,360,0,Rural,Approved
2,APP003,Male,No,Graduate,No,11654,2278,257,180,1,Rural,Approved
3,APP004,Female,No,Not Graduate,Yes,5527,2757,76,180,1,Urban,Approved
4,APP005,Female,No,Not Graduate,Yes,9527,4392,81,240,0,Rural,Rejected

In [3]:
df.info()

df.describe()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Application_ID     150 non-null    object
 1   Gender             150 non-null    object
 2   Married            150 non-null    object
 3   Education          150 non-null    object
 4   Self_Employed      150 non-null    object
 5   ApplicantIncome    150 non-null    int64
 6   CoapplicantIncome  150 non-null    int64
 7   LoanAmount         150 non-null    int64
 8   Loan_Amount_Term   150 non-null    int64
 9   Credit_History     150 non-null    int64
 10  Property_Area      150 non-null    object
 11  Loan_Status        150 non-null    object
dtypes: int64(5), object(7)
memory usage: 14.2+ KB

Application_ID       0
Gender               0
Married              0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [4]:
df = pd.get_dummies(
    df,
    columns=[
        "Gender",
        "Married",
        "Education",
        "Self_Employed",
        "Property_Area"
    ],
    drop_first=True
)

df.head()

,Application_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Male,Married_Yes,Education_Not Graduate,Self_Employed_Yes,Property_Area_Semiurban,Property_Area_Urban
0,APP001,5657,1143,238,180,0,Rejected,True,True,True,True,False,False
1,APP002,5582,1905,179,360,0,Approved,False,True,False,True,False,False
2,APP003,11654,2278,257,180,1,Approved,True,False,False,False,False,False
3,APP004,5527,2757,76,180,1,Approved,False,False,True,True,False,True
4,APP005,9527,4392,81,240,0,Rejected,False,False,True,True,False,False

In [5]:
df["Loan_Status"] = df["Loan_Status"].map({
    "Rejected":0,
    "Approved":1
})

In [6]:
X = df.drop(columns=["Application_ID","Loan_Status"])

y = df["Loan_Status"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [8]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [9]:
y_pred = model.predict(X_test)

In [10]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

Accuracy : 1.0

In [11]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[ 1  0]
 [ 0 29]]

In [12]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00        29

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [13]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

comparison.head(10)

   Actual  Predicted
0       1          1
1       0          0
2       1          1
3       1          1
4       1          1
5       1          1
6       1          1
7       1          1
8       1          1
9       1          1

In [14]:
print(X.columns)

Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Gender_Male', 'Married_Yes',
       'Education_Not Graduate', 'Self_Employed_Yes',
       'Property_Area_Semiurban', 'Property_Area_Urban'],
      dtype='object')

In [19]:
new_customer = pd.DataFrame({
    "ApplicantIncome":[2000],
    "CoapplicantIncome":[500],
    "LoanAmount":[1500],
    "Loan_Amount_Term":[360],
    "Credit_History":[1],
    "Gender_Male":[1],
    "Married_Yes":[1],
    "Education_Not Graduate":[0],
    "Self_Employed_Yes":[0],
    "Property_Area_Semiurban":[1],
    "Property_Area_Urban":[0]
})

prediction = model.predict(new_customer)

if prediction[0] == 1:
    print("Loan Approved")
else:
    print("Loan Rejected")

Loan Rejected