<a href="https://colab.research.google.com/github/himanshusar123/-Machine-Learning-Quiz-Classification-or-Regression-/blob/main/Day_6__Uss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Employee_Salary_Dataset.xlsx to Employee_Salary_Dataset (1).xlsx

In [3]:
import pandas as pd

df = pd.read_excel("Employee_Salary_Dataset.xlsx")

df.head()

  Employee_ID  Years_of_Experience  Salary
0      EMP001                  9.8  100709
1      EMP002                 11.3  117062
2      EMP003                  3.7   50129
3      EMP004                 10.3  113485
4      EMP005                  1.8   39212

In [4]:
df.info()

df.describe()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          100 non-null    object
 1   Years_of_Experience  100 non-null    float64
 2   Salary               100 non-null    int64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.5+ KB

Employee_ID            0
Years_of_Experience    0
Salary                 0
dtype: int64

In [5]:
X = df[["Years_of_Experience"]]

y = df["Salary"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [6]:
model = LinearRegression()

In [9]:
model.fit(X_train, y_train)

LinearRegression()

In [10]:
y_pred = model.predict(X_test)

In [12]:
experience = [[8.5]]

predicted_salary = model.predict(experience)

print("Predicted Salary: ₹", int(predicted_salary[0]))

Predicted Salary: ₹ 94214

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [13]:
comparison = pd.DataFrame({
    "Actual Salary": y_test.values,
    "Predicted Salary": y_pred.astype(int)
})

comparison.head(10)

   Actual Salary  Predicted Salary
0         149085            145291
1         125916            124009
2          96239             92511
3          61047             56757
4          41387             43988
5          57856             59311
6          93789             97619
7         111857            107834
8          93606             98470
9         100709            105281

In [14]:
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))

print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

print("R2 Score:", r2_score(y_test, y_pred))

Mean Absolute Error: 3044.0276472343808
Mean Squared Error: 10842662.985266645
R2 Score: 0.9914310494906821